// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  sidebar: [
    "intro",
    {
      type: "category",
      label: "Overview",
      items: ["overview/introduction"],
    },
    {
      type: "category",
      label: "Setup",
      items: ["setup/setup-instructions", {
        type: "category",
        label: "Standalone",
        items: ["setup/standalone/standalone-setup", "setup/standalone/docker-setup_standalone"]
      },{
        type: "category",
        label: "Github Submodules",
        items: ["setup/github-submodule/submodule-instructions"]
      }],
    },
    {
      type: 'category',
      label: 'API Endpoints',
      items: [
        {
          type: 'doc',
          id: 'api/api-endpoint-overview',
          label: 'API Endpoint Overview',
        },
        {
          type: 'category',
          label: ' ',
          customProps: { method: 'GET' },
          items: [
            {
              type: 'doc',
              id: 'api/get/validate-session',
              label: 'Validate Session',
              customProps: { method: 'GET' },
            },
          ]
        },
        {
          type: 'category',
          label: ' ',
          customProps: { method: 'POST' },
          items: [
            {
              type: 'doc',
              id: 'api/post/register',
              label: 'Register',
              customProps: { method: 'POST' },
            },
            {
              type: 'doc',
              id: 'api/post/login',
              label: 'Login',
              customProps: { method: 'POST' },
            },
            {
              type: 'doc',
              id: 'api/post/request-reset-password',
              label: 'Password Reset Request',
              customProps: { method: 'POST' },
            },
            {
              type: 'doc',
              id: 'api/post/reset-password',
              label: 'Password Reset',
              customProps: { method: 'POST' },
            },
            {
              type: 'doc',
              id: 'api/post/verify-mfa',
              label: 'Verify MFA',
              customProps: { method: 'POST' },
            },
            {
              type: 'doc',
              id: 'api/post/enable-mfa',
              label: 'Enable MFA',
              customProps: { method: 'POST' },
            },
            {
              type: 'doc',
              id: 'api/post/recover-mfa',
              label: 'Recover MFA',
              customProps: { method: 'POST' },
            },
            {
              type: 'doc',
              id: 'api/post/logout',
              label: 'Logout',
              customProps: { method: 'POST' },
            },
          ]
        },
        {
          type: 'category',
          label: ' ',
          customProps: { method: 'PUT' },
          items: [
            {
              type: 'doc',
              id: 'api/put/update-user',
              label: 'Update User',
              customProps: { method: 'PUT' },
            },
            {
              type: 'doc',
              id: 'api/put/update-email',
              label: 'Update Email',
              customProps: { method: 'PUT' },
            },
          ]
        },
        
      ],
    },
  ]
};

export default sidebars;
